name: Update gom.html

on:
  schedule:
    - cron: "0 */12 * * *" # Her 12 saatte bir çalışır
  push:
    branches:
      - main
  workflow_dispatch: # Manuel çalıştırma için

jobs:
  update-gom-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run gom.py
      run: python gom.py
      env:
        GITHUB_ACTIONS: true

    - name: Commit and push changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add gom.html
        git commit -m "Update gom.html with latest series data" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
