name: DiziGom Scraper

on:
  schedule:
    - cron: '0 */12 * * *'  # Her 12 saatte bir
  workflow_dispatch:  # Manuel çalıştırma için
  push:
    branches: [ main ]

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run scraper
      run: python gom.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Değişiklikleri kontrol et
        if git diff --quiet; then
          echo "Değişiklik yok, commit atlanacak."
        else
          git add gom.html
          git commit -m "📦 Gom.html güncellendi - $(date +'%Y-%m-%d %H:%M')"
          git push
        fi
