name: Run Scraper

on:
  workflow_dispatch:   # Manuel çalıştırmak için
  push:                # Repo'ya push olunca çalışır

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: |
          python scraper.py
