name: Scrape PuhuTV

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Her gün 00:00'da çalışır
  workflow_dispatch: # Manuel tetikleme için

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Tüm commit geçmişini al

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 tqdm

    - name: Run PuhuTV scraper
      run: python puhutv.py

    - name: Commit and push puhutv.html
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add puhutv.html
        git commit -m "Update puhutv.html with latest scrape" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Handle failure
      if: failure()
      run: echo "Scraper failed, check logs for details"
