name: Scrape PuhuTV

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *' # Her 3 saatte bir çalışır (00:00, 03:00, 06:00, 09:00, 12:00, 15:00, 18:00, 21:00 UTC)
  workflow_dispatch: # Manuel tetikleme için

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0 # Tüm commit geçmişini al

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 tqdm

    - name: Run PuhuTV scraper
      run: python puhutv.py

    - name: Commit and push puhutv.html
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add puhutv.html
        git commit -m "Update puhutv.html with latest scrape" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Handle failure
      if: failure()
      run: echo "Scraper failed, check logs for details"
